### ISSUE TITLE
Generator error: Client responses with body

### ISSUE THREAD

**Issue by mcristina422** [deepmap/oapi-codegen#10]
The return type in the client is `(*http.Response, error)`
https://github.com/deepmap/oapi-codegen/blob/beb7bf6aeecdd3f4696abee63eca5f7c205885d3/pkg/codegen/templates/client.tmpl#L12

While the interface is always expecting `error`
https://github.com/deepmap/oapi-codegen/blob/a913c9ad69267756e5efad105fa72fb38c6cc897/pkg/codegen/templates/server-interface.tmpl#L22
I recommend adding this 
```golang
// Compile time check to ensure the client satisfies the server interface
var _ ServerInterface = (*Client)(nil)
```
to the top of https://github.com/deepmap/oapi-codegen/blob/beb7bf6aeecdd3f4696abee63eca5f7c205885d3/pkg/codegen/templates/client.tmpl#L1
https://medium.com/@matryer/golang-tip-compile-time-checks-to-ensure-your-type-satisfies-an-interface-c167afed3aae

**Comment by deepmap-marcinr** [comment]
If I understand this issue correctly, this is actually by design.

The client and server interfaces are not identical, since we still require some work to be done by the caller.

For the server interface, you are expected to put the response body on the context in the handler function. The response handling is out of our hands. Your handler returns an error if there was an error in the processing of the response, not if there's an error returned via HTTP. The semantics are the same as returning error from an echo handler.

For the client interface, we generate the request for you, and hand back an unprocessed http.Response for you to interpret. This is where the asymmetry comes from.

**Comment by mcristina422** [comment]
Ah you're right! Sorry I didn't describe the problem I was attempting to solve better.

In the project I was working on I was purely using this as a client and was ignoring the server aspect. I was experimenting with creating additional generators with implementations for interpreting the`http.Response` by parsing it as as yaml or json into model representations. I got carried away and confused with code reuse
