### ISSUE TITLE
remove *string and pointer to objects in general for optional params

### ISSUE THREAD

**Issue by nfallahi** [deepmap/oapi-codegen#1074]
If a field like a string is optional, in my opinion it should just be defined as :

`foo string ``json:"foo,omitempty"`
`
I think defining it as *string is just confusing and ends up sending a lot of empty values cause of something like this: https://go.dev/play/p/1Omq9D8ERvr

**Comment by stnokott** [comment]
I know this is a pretty old issue, but I had the same thoughts as @nfallahi , so I stumbled upon this issue.

If possible, I'd request a re-elaboration of why this is a design decision with the following thoughts in mind:

---

The issue was closed with the reasoning that

> This way it's clear when a value isn't sent vs it's sent but empty

I can't fully get behind that argument. After all, **OpenAPI specs explicitly allow defining field nullability**, so when a field is defined as non-nullable in the spec and it isn't sent from the API, this should produce an error when parsing the response.
For that reason, pointers in the response struct should only be used for nullable types in my eyes.

In summary, there would be these scenarios for the generated code in terms of handling response fields:

| Field nullable in spec? | Field in generated response struct | Field in API response | Behaviour of generated code |
| --- | --- | --- | --- |
| ✓ | pointer | not sent | set value to nil, return no error |
| ✓ | pointer | sent, but empty | set value to nil, return no error |
| ✓ | pointer | sent and filled | set value to parsed API response |
| x | struct | not sent | return error when processing API response internally |
| x | struct | sent, but empty | return error when processing API response internally |
| x | struct | sent and filled | set value to parsed API response |

I feel like this would be a valid behaviour pattern, would lead to comprehensible results and would make processing generated response much easier.

If I understand the initial comment by @jamietanna correctly, the reasoning behind this design decision is to enable the user to differentiate between scenario 1 and 2. In my eyes, the client doesn't need to differentiate between these though as an "empty" response is just as useful as a response that doesn't exist. (But maybe I misunderstood your definition of "empty")

If you have time, @jamietanna , I'd love to hear your opinion on this.

Thanks a lot!

**Comment by jamietanna** [comment]
Hey, thanks for the thoughtful message. Before I get to replying fully, mind checking if the [recently released Nullable support](https://github.com/deepmap/oapi-codegen/releases/tag/v2.1.0) may help with this use-case?

**Comment by stnokott** [comment]
Wow, swift reply!

Yeah, I checked and tried that already.

The issue I have is not with nullable fields, but with non-nullable fields which are stored as pointers too.
That causes a lot of client-side overhead when processing response structs and is not required in my eyes (see table above).

While the feature you mention is great, it only adds functionality to fields which are nullable and does not help with reducing processing overhead for non-nullable fields.

**Comment by stnokott** [comment]
Hey @jamietanna did you have time yet to think about my suggestion?
