### ISSUE TITLE
remove echo dependancy for chi server

### ISSUE THREAD

**Issue by aca** [deepmap/oapi-codegen#125]
Chi server shares same functions in runtime package which uses echo.
Removing unnecessary dependency against echo would make chi server more simple

**Comment by qmuntal** [comment]
`echo` is used for two purposes in `pkg/runtime`:

1. In `EchoRouter` interface methods
2. In `BindStyledParameter` and `BindQueryParameter` to return `echo.HTTPError` instead of a plain error.

The `EchoRouter` interface could be moved from the runtime to the echo specific templates, as it is not used in the runtime.

The two other methods returning echo.HTTPError could return instead a plain `fmt.Errorf`, as the auto generate code calling them are already adding the necessary context to the error:

***echo server***
```go
err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
if err != nil {
    return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
}
```

***chi server***
```go
err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
if err != nil {
    http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
    return
}
```
