### ISSUE TITLE
Generating types into a different package?

### ISSUE THREAD

**Issue by suntong** [deepmap/oapi-codegen#1259]
Giving the dilema that I'm facing in https://github.com/ThreeDotsLabs/wild-workouts-go-ddd-example/issues/70, one possible/clean solution is to generate types into a different package, so as to make it easier to adopt the [Repository Pattern](https://threedots.tech/post/repository-pattern-in-go/):

> Keeping logic of your application along with your database logic makes your application much more complex, hard to test, and maintain.
> 
> There is already a proven and simple pattern that solves these issues. The pattern that allows you to separate your application logic from database logic.

Would that be possible in the future?  
Otherwise, the (almost) same type need to be redefine in domain yet again, which is what the wild-workouts-go-ddd-example currently doing, and should better be avoided. 

Thanks for consideration.

**Comment by nickajacks1** [comment]
The cleanest way in my opinion to put the models/types in a separate package is to do what's done [in this example](https://github.com/deepmap/oapi-codegen/tree/master/internal/test/externalref) and split off your component definitions into its own spec file.  You can then generate code from that in a standalone models package.

From the main openapi spec file, refer to these components like so:
`$ref: ./packageB/spec.yaml#/components/schemas/ObjectB`
In the main generation config, you can then set the import-mapping option to point to your model package.
Also, make sure you set `skip-prune: true` for your model generation, otherwise you'll get an empty generated file.

**Comment by suntong** [comment]
Thanks
