### ISSUE TITLE
Generate struct with io.Reader as type

### ISSUE THREAD

**Issue by rohit-32** [deepmap/oapi-codegen#132]
for something like in specs.yml
```
image:
   type: string
   format: binary
```
the codegen generates struct with field
```
type EventImage struct {
	Image     *string `json:"image,omitempty"`
}
```
which is wrong TBH
it should be 
type EventImage struct {
	Image     io.Reader `json:"image,omitempty"`
}
```

**Comment by deepmap-marcinr** [comment]
I have to produce a data type into which Echo's ctx.Bind() function can actually unmarshal the data. io.Reader isn't a valid destination. I need to experiment, but I think it may be possible to use a []byte instead of string here - not 100% sure about that.

**Comment by deepmap-marcinr** [comment]
If you specify the string format as "bytes" or "binary", it will be []byte.

The io.Reader is hidden from me, and doesn't make sense in the way that JSON and other common formats are deserialized, so it'll never be a reader, sadly. I see the purpose behind it, but since streaming reads aren't possible with all these unmarshalling layers we're using, we'd still have to back it with a Buffer or something, defeating the purpose.
