### ISSUE TITLE
/swagger.json endpoint

### ISSUE THREAD

**Issue by lukekhamilton** [deepmap/oapi-codegen#18]
Hey guys,

Do you have a recommended way to add a /swagger.json endpoint?
Thanks. 
L

**Comment by deepmap-marcinr** [comment]
The generated code has the swagger spec embedded in it (see the GetSwagger function, see https://github.com/deepmap/oapi-codegen/blob/master/examples/petstore-expanded/api/petstore.gen.go#L375

You could declare a new path for /swagger.json and in the handler, you call GetSwagger and marshal that to JSON, since the openapi3.Swagger struct is designed to be json serialized.

Your handler would be very simple:
ctx.JSON(http.StatusOk, api.GetSwagger())

It's inefficient to do that too often so you might want to cache the json string, but that's the general idea.

**Comment by lukekhamilton** [comment]
ok thanks heaps!

**Comment by deepmap-marcinr** [comment]
Man, so many special cases to consider. I’ll fix it shortly. The fix is
easy. I’m adding a unit test for every known failure so that we don’t
regress

**Comment by lukekhamilton** [comment]
Yeah like whats sort of special cases you speak of? Maybe I can help...

**Comment by deepmap-marcinr** [comment]
I mis-sent this reply to the wrong email, sorry.

**Comment by lukekhamilton** [comment]
ok now that makes sense. Would you guys be open to having this as a feature? Be nice to be able to offer a public /swagger.json endpoint that also isn't minified too?

**Comment by deepmap-marcinr** [comment]
I think perhaps an easy to copy/paste example might be the way to go, since
I don't want to insert any API's behind anyone's back. For instance,
someone might not want to serve swagger.json without a security credential,
so I couldn't make it always work as desired. Another options would be to
do it with some simple middleware you can install yourself.

This is still a young project, and I add stuff as I discover a lack of it
in my production systems

-- Marcin

**Comment by lukekhamilton** [comment]
yeah totally get that. I've got it all running now. Just can see myself using this pkg quite a bit. Might have a look at building a middleware where I have space.

**Comment by StevenACoffman** [comment]
If you already have the gzipped json, and most clients accept gzipped content, it is inefficient to call GetSwagger just to turn it back into JSON and then run it through a middleware to gzip it again. However, the generated embedded spec is currently inaccessible. You would need to add a method to access it, or a handler something like this:
```
func Handler(si ServerInterface) http.Handler {
        return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil { // ok, this is wrong but you get the idea
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
        w.Header().Set("Content-Encoding", "gzip")
        http.ServeContent(w, req, name, modTime, bytes.NewReader(gzipFile.GzipBytes()))
            http.ServeContent(w, r, "foo.txt", time.Now(),
                strings.NewReader("I am some content.\n"))
        }))
}
```
