### ISSUE TITLE
Runtime doc support

### ISSUE THREAD

**Issue by wangyoucao577** [deepmap/oapi-codegen#197]
Hi there,     
I'm trying to use this project to generate `Go` codes for openapi 3.0, and it's excellent. The generated codes are quite simple and straightforward. The most important advantage to me is that it supports [go-chi/chi](https://github.com/go-chi/chi) as web framework that 100% compatible with `net/http`.     
However, when I go through the generated code I didn't find any support on runtime doc. Previously when I use [go-swagger](https://github.com/go-swagger/go-swagger) for openapi 2.0, it has built-in redoc that can be accessed directly by `/docs` by default. It there any way to have similar feature on `oapi-codegen` too? It'll be very helpful if users can find doc along with restapi in same host. 
Thanks in advance!

**Comment by jamietanna** [comment]
I'm going to speak for @deepmap-marcinr and say that I don't think this fits inside the vision for the project, which aims to keep things as straightforward as possible.

Personally, I would always recommend against keeping it hosted in the API, as the API may be internal-only, and it introduces more risk of security issues, as you're now serving a web app, rather than just a pure API, but that's just me!

This is something that I _could_ see a path to technically doing it using ie https://github.com/stoplightio/elements - I'm happy to get a WIP put up to show what this could look like, behind optional configuration?

**Comment by jamietanna** [comment]
Example - horribly hacky - code example at https://github.com/deepmap/oapi-codegen/compare/master...jamietanna:oapi-codegen:feature/docs?expand=1, which when renders:

![Screenshot 2022-08-30 at 15 40 23](https://user-images.githubusercontent.com/3315059/187466630-0414e0ab-27e3-406c-a2c9-4affbe39df3c.png)

Notice that we have to disable the request validation middleware - this is required because adding a handler for `/doc` fails for:

```
curl localhost:8080/doc -i
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 30 Aug 2022 14:43:30 GMT
Content-Length: 32

no matching operation was found
```

Because of this, it's unlikely that we can support this out-of-the-box, as in a lot of cases, the OpenAPI needs to change to add this.

We could package up a helper to convert a `GetSwagger` call to an HTTP response, but that again may be out of scope of the repo (for now) - but would be great to see it as a separate library! (Maybe I'll write it 😁)

**Comment by deepmap-marcinr** [comment]
I think that runtime docs are very valuable, but this really is a difficult problem. We have the same problem with our internal API's at my employer, which are based on oapi-codegen boilerplate. We have solved it by having our API servers serve the API spec file as JSON, then we run the swagger-ui container (https://swagger.io/tools/swagger-ui/) and point it at our API spec. It works great, and means we don't have to write the code to generate this UI.

swagger-UI is the only one which generates interactive docs with a "Try It" button, which is really useful. The static doc generators do not. Furthermore, they all require npm or Java or some other enormous dependency, which is simply out of the scope of this project.

You can always create a `/docs` endpoint on your server which does an HTTP/302 redirect to your docs which are hosted by swagger-ui.

**Comment by jamietanna** [comment]
I've shipped the above code into https://gitlab.com/jamietanna/openapi-doc-http-handler so hopefully that may be an easier drop-in replacement rather than one we need to maintain as part of this project?

Elements allows a try-it functionality too, and as it supports OpenAPI 3.1 + other handy features I generally use that over Swagger UI

**Comment by suntong** [comment]
> I've shipped the above code into https://gitlab.com/jamietanna/openapi-doc-http-handler

hmm... would you show how to use it please?   
I was trying to make use of it myself, but these are what I got:

```
$ go mod tidy
go: finding module for package gitlab.com/tanna.dev/openapi-doc-http-handler
go: downloading gitlab.com/tanna.dev/openapi-doc-http-handler v0.1.1
go: server imports
        gitlab.com/tanna.dev/openapi-doc-http-handler: module gitlab.com/tanna.dev/openapi-doc-http-handler@latest found (v0.1.1), but does not contain package gitlab.com/tanna.dev/openapi-doc-http-handler

# or, 

$ go mod tidy
go: finding module for package gitlab.com/jamietanna/openapi-doc-http-handler
go: downloading gitlab.com/jamietanna/openapi-doc-http-handler v0.1.1
go: server imports
        gitlab.com/jamietanna/openapi-doc-http-handler: module gitlab.com/jamietanna/openapi-doc-http-handler@latest found (v0.1.1), but does not contain package gitlab.com/jamietanna/openapi-doc-http-handler

```

**Comment by jamietanna** [comment]
@suntong apologies, I've fixed the modules import path, please retry again with the latest README for the module

**Comment by suntong** [comment]
Love it. Thanks!
