### ISSUE TITLE
error generating code: error formatting Go code when using 3gpp 5g spec TS29571_CommonData.yaml

### ISSUE THREAD

**Issue by lezixiao** [deepmap/oapi-codegen#41]
I have two questions.
 a) ./oapi-codegen TS29571_CommonData.yaml > TS29571_CommonData.go                             
error generating code: error formatting Go code: 24:6: expected 'IDENT', found 5 (and 8 more errors)
b) how to use oapi-codegen for TS29502_Nsmf_PDUSession.yaml which refer to TS29571_CommonData.yaml
I attached TS29571_CommonData.yaml TS29571_CommonData.go and TS29502_Nsmf_PDUSession.yaml

[yamlAndGo.zip](https://github.com/deepmap/oapi-codegen/files/3434537/yamlAndGo.zip)

**Comment by deepmap-marcinr** [comment]
This code is breaking because it has schema names which I did not consider - things like your schema named `5Qi`. This turns into a Go type named 5Qi, and go types may not start with numbers.  I think the fix will be to detect those cases and prepend a letter. Maybe if it starts with a number, I'll prepend an N or something, so that 5Qi becomes N5Qi.

**Comment by deepmap-marcinr** [comment]
This is fixed in 2177b2dc5487b76933051ccab327922d6d5ab204

You can "go get github.com/deepmap/oapi-codegen/cmd/oapi-codegen@2177b2dc5487b76933051ccab327922d6d5ab204" to fetch it until I push the next release.

This fixes the type errors, however, one of your files refers to the other via an external reference, and our underlying libraries don't support that yet. You'll have to copy some schemas from one to the other so you don't have cross-file references.
