### ISSUE TITLE
Options for supporting anyOf or oneOf

### ISSUE THREAD

**Issue by weberr13** [deepmap/oapi-codegen#46]
Our organization is looking at using oapi-codegen and we have a need to support oneOf and are looking into a few potential ways to do so.  I want to get feedback about which best fits into the oapi-codegen vision.  

First of all, there would need to be discriminators used for any polymorphic objects (https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/).  

With that in mind this is my proposal that I will implement if it looks good:

for the example spec (fragment):
```yaml
paths: 
  /mything:
    put:
      summary: Put my thing
      operationId: putMyThing
      requestBody:
        description: Contents of thing
        required: true
        content:
          application-json:
            schema:
              discriminator:
                 propertyName: thingType
              oneOf:
                - $ref: "#/components/schemas/EasyThing"
                - $ref: "#/components/schemas/HardThing"
```

would generate an interface with

```go
type ServerInterface interface {
	// Put my thing// (PUT /mything)
	PutMyThing(ctx echo.Context, discriminator string) error
}
```

Then the user could use the information gleaned from the discriminator to do something like:

```go
m := make(map[string]interface{})
err := json.Unmarshal(ctx.Request().Body, &m)
switch m[discriminator] {
	case "easyThing":
		{
			doEasyThingStuff(ctx,m)
		}
	case "hardThing":
		{
			doHardThingStuff(ctx,m)
		}
}

```

**Comment by deepmap-marcinr** [comment]
This sounds like the right answer, but it's difficult to do correctly, and it seems to imply that the discriminator is necessary, which it doesn't seem to be the case in the OpenAPI specification. It'll be a lot of work to do this - as it needs to be handled separately for bodies, parameters, etc.

It sounds like some folks are using this package with specs that they don't control, so if we make the discriminator mandatory, then they might have trouble. Make it optional, and if there isn't one, the user is on their own. Also, generating intelligent type names for each unnamed member in oneOf or anyOf is tricky.

**Comment by weberr13** [comment]
Yeah, it is difficult in golang to do purely agnostic type generation but I'm tackling it here:  https://github.com/weberr13/go-decode and once it is working I will modify the code generation behind an option to generated the appropriate constructors/factories so that the decode step can be automatic and support collections and polymorphic oneOf/anyOf.

**Comment by deepmap-marcinr** [comment]
Your link above doesn't work.

Could you give an example of what output might look like for a oneOf composed of two unnamed types?

**Comment by weberr13** [comment]
I apologize for the broken link.  Currently I'm tied up in red tape RE: this feature and I will update as soon as I get past it.  As for unnamed types I can only imagine it stays interface and that is what I have locally.  When it is discriminated with ref's you can get something like this:

```golang
          // CatAlive defines model for CatAlive.
            type CatAlive struct {
                AliveSince *time.Time `json:"alive_since,omitempty"`
                Name       *string    `json:"name,omitempty"`
                Type       *string    `json:"type,omitempty"`
            }

            // CatDead defines model for CatDead.
            type CatDead struct {
                Cause     *string    `json:"cause,omitempty"`
                DeadSince *time.Time `json:"dead_since,omitempty"`
                Name      *string    `json:"name,omitempty"`
                Type      *string    `json:"type,omitempty"`
            }           
           func TypeFactory(kind string) (decode.Decodeable, error) {
                fm := map[string]func() decode.Decodeable{
                        "cat_alive": NewCatAlive,

                        "cat_dead": NewCatDead,
                }
                f, ok := fm[kind]
                if !ok {
                        return nil, fmt.Errorf("cannot find type %s", kind)
                }
                return f(), nil
            }

            func NewCatAlive() decode.Decodeable {
                return &CatAlive{
                        Type: "cat_alive",
                }
            }

            func (r CatAlive) Discriminator() string {
                return r.Type
            }

            func NewCatDead() decode.Decodeable {
                return &CatDead{
                        Type: "cat_dead",
                }
            }

            func (r CatDead) Discriminator() string {
                return r.Type
            }           type getCatStatusResponse struct {
                Body         []byte
                HTTPResponse *http.Response
                JSON200      *decode.Decodeable
                XML200       *interface{}
                YAML200      *struct {
                        // Embedded struct due to allOf(#/components/schemas/CatAlive)
                        CatAlive
                        // Embedded struct due to allOf(#/components/schemas/CatDead)
                        CatDead
                }
                JSONDefault *Error
            }

// ParsegetCatStatusResponse parses an HTTP response from a GetCatStatusWithResponse call
            func ParsegetCatStatusResponse(rsp *http.Response) (*getCatStatusResponse, error) {
                bodyBytes, err := ioutil.ReadAll(rsp.Body)
                defer rsp.Body.Close()
                if err != nil {
                        return nil, err
                }

                response := &getCatStatusResponse{
                        Body:         bodyBytes,
                        HTTPResponse: rsp,
                }

                switch {
                case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
                        response.JSON200, err = decode.UnmarshalJSON(bodyBytes, "type", TypeFactory)
                        if err != nil {
                                return nil, err
                        }
                case strings.Contains(rsp.Header.Get("Content-Type"), "yaml") && rsp.StatusCode == 200:
                        response.YAML200 = &struct {
                                // Embedded struct due to allOf(#/components/schemas/CatAlive)
                                CatAlive
                                // Embedded struct due to allOf(#/components/schemas/CatDead)
                                CatDead
                        }{}
                        if err := yaml.Unmarshal(bodyBytes, response.YAML200); err != nil {
                                return nil, err
                        }
                case strings.Contains(rsp.Header.Get("Content-Type"), "json"):
                        response.JSONDefault = &Error{}
                        if err := json.Unmarshal(bodyBytes, response.JSONDefault); err != nil {
                                return nil, err
                        }
                }

                return response, nil
            }

```

**Comment by deepmap-marcinr** [comment]
Do you have decode.Decodeable somewhere public?

I'm wondering whether handling allOf/anyOf belongs in here, or in a higher, smarter layer in the application.

We could make an executive decision here that we require a discriminator, and can use one of the extended attributes to express a map of discriminator value to type. This would make us not fully general, but, easy to use. Would this solve your use case? It would also be a lot easier to support multiple content types this way, since the code would be similar between JSON and YAML, for example.

If we need to support the no-discriminator case, I would punt the decision to the application layer. Functions which accept as input anything with a `oneOf` would expect a callback which returns its type - either as a string, or instantiated via interface{}, whatever - something we can switch on when we need to have a value.

**Comment by weberr13** [comment]
Yeah, the decoder package will be open sourced very soon but essentially decode.Decoder is simply an interface with a "Discriminator() string" function.  The UnmarshalJSON() is the key function from it but adding YAML/XML is also a possibility once I get it open sourced.  

go-decode is a reflection based library like github.com/mitchellh/mapstructure but it requires those discriminators so that the underlying classes can be directly created (through that factory function in the generated code above).   In order to use it I needed to code generate the constructor (NewDeadCat) and the Factory (for all of the possible "oneOf"/"anyOf" structures.  The call to UnmarshalJSON() is not the responsibility of the oapi-codegen but without generating the factory/etc it becomes difficult to use.  

The way I have my local code written the old functionality of creating naked interface{} pointers is retained when the discriminators are not found.  I think this is a best of both worlds situation.

**Comment by weberr13** [comment]
Just an update.  I continue to work on refining my proposal and I should be able to reopen the MR and publish the go-decode stuff very soon.  I also want to bring @bonnyr into this discussion as he is working with me on developing it.

**Comment by VadimKulagin** [comment]
Is there any news on the implementation of the oneOf feature in the client?

At first I planned to implement this myself, but then I found this issue and now I am waiting for implementation.

I think the implementation should consider the following cases:
1. If the `discriminator` field is not specified in the schema, the resulting type of the object should be determined by validating the data against the list of oneOf schemas. And if EXACTLY ONE schema was determined – its type should be used for unmarshaling. Otherwise, there should be a validation error.
2. If the `discriminator` field is specified only with `propertyName`, then the input data should first be temporarily unmarshaled into the temporary structure
```go
struct {
  <propertyName> string
}
```
then we need to determine the type from `<propertyName>` field and use it for unmarshaling.
3. If the `discriminator` field is specified with the `mapping` field, then we need to perform step 2 using the type name from the `mapping` field.

And it is worth considering the following quote from the specification:
> If the discriminator value does not match an implicit or explicit mapping, no schema can be determined and validation SHOULD fail. 
https://swagger.io/specification/#discriminatorObject

**Comment by deepmap-marcinr** [comment]
This is an incredibly annoying thing to support in Go. We may get there one day, but I can't promise anything about timelines.

We don't actually need to unmarshal into a pre-defined struct to find the discriminator, we can do it along the lines of what the kin-openapi filter does; unmarshal to a generic interface{} and find the field via reflection or direct inspection based on the schema.

It's certainly doable, but given that there can be anonymous types in schemas, and we can't unmarshal into anonymous types in a useful way, we need to come up with a implicit type generation system like we did for AdditionalProperties.

It's a big feature!

**Comment by VadimKulagin** [comment]
> We don't actually need to unmarshal into a pre-defined struct to find the discriminator, we can do it along the lines of what the kin-openapi filter does; unmarshal to a generic interface{} and find the field via reflection or direct inspection based on the schema.

I think that using a temporary structure with one "propertyName" field can perform unmarshaling faster with less memory allocation than unmarshaling into `interface{}` or `map`. But it is worth testing.

> given that there can be anonymous types in schemas, and we can't unmarshal into anonymous types in a useful way, we need to come up with a implicit type generation system like we did for AdditionalProperties.

I think it's worth keeping in mind the following statement from the spec:
> When using the discriminator, inline schemas will not be considered.

From this it follows that if the `discriminator` field is specified, we should know the type name.

And from this it follows that the main difficulty with determining the type arises in case No. 1.

Considering that in case No. 1 the determination of the appropriate schema should be performed in runtime, we can pre-generate a private variable of type `map[jsonPointerToASchema]func() instanceOfGeneratedType` or `map[jsonPointerToASchema]exampleInstanceOfGeneratedType` inside the package, which can be used to determine the resulting type.

I understand that this is a big feature. I just decided to offer a couple of my thoughts on this subject 🙂

**Comment by deepmap-marcinr** [comment]
Ahh, I didn't notice the predefined type qualification. That would be much easier.

**Comment by bonnyr** [comment]
We have made several passes at implementing this and have a WIP version in our fork, which may be ready for review soon. 

The discussion above is something we had to deal with directly and with @weberr13's go-decode library we have a way (opinionated) to support oneOf successfully (using reflection) .

We chose to enforce using the `discriminator` field so that we can revert to generating the existing code for specs that did not use that field. This can change to essentially default to using the schema name as the discriminator value (as described in the spec).

Note that our implementation does not allow/support using `oneOf` with anonymous schemas.

**Comment by benfdking** [comment]
Has anyone looked at how GRPC implements `oneOf`. It does like the example I have added. Is there any problem with that? Also does the validator work for oneOf out of curiosity?

```go
type Parent interface {
  thing isThing_Thing
}


type isThing_Thing interface {
	isThing_Thing()
}

type isThing_1 struct {
}

type isThing_2 struct {
}

func (*isThing_1) isThing_Thing() {}

func (*isThing_2) isThing_Thing() {}
```

**Comment by orishoshan** [comment]
@benfdking Indeed that could work for output compile-time validation - I came to a similar conclusion as you. I looked into adding it to oapi-codegen just now, however in order to do that you would need to know which models, in advance of the code generation, that function should be added to. There are two tricky parts:
* The current design couples the iteration over everything with the code generation, and since Go doesn't support generics, this code is written many times over to support Properties, ResponseBodies, Schemas, anonymous request parameters, etc.
* The easy way to do this would be to generate an ID that identifies the model, and then later use it during code generation to determine whether you should add the `isThing_Thing()`. But this is actually a lot of work since there are many ways to specify models under a oneOf (you could use a ref, but you can also anonymously specify a schema inline), and many places where you could do this.

So while it's certainly _possible_, it's quite a lot of work at the present moment.

**Comment by deepmap-marcinr** [comment]
Right, it's also why I haven't done this yet myself. It's an awful lot of
work, and also, error prone work with lots of assumptions. We can simply
store it as RAWJson and let the user deal with it. I wrote this library to
help with the common, easy cases more so than trying to cover all the
bases, since covering all the bases leads to really complex, difficult to
use tools.

**Comment by orishoshan** [comment]
Frustratingly, it feels like this tool would benefit a lot from being written in another language :( One that supports generics or that is duck-typed.

**Comment by uri200** [comment]
@deepmap-marcinr , with increase usage of swagger 3.0 I am seeing more `discriminators` on specs. Would @weberr13 implementation make sense, even if we were going to assume that discriminator is necessary and present?

**Comment by jamietanna** [comment]
I believe this is supported now - feel free to re-open if the discriminator support doesn't fit what's needed!
