### ISSUE TITLE
Allow marking custom vendored JSON types as JSON

### ISSUE THREAD

**Issue by jamietanna** [deepmap/oapi-codegen#581]
In https://github.com/deepmap/oapi-codegen/blob/6a3482493b5731b60c267147522ec3aaa09fc3a3/pkg/codegen/operations.go#L54-L61 we're checking for specifically JSON, but we may have:

- `application/json-patch+json`
- `application/vnd.something+json`
- `application/json; charset=UTF-8`

We should look at adding support for these, too

**Comment by jamietanna** [comment]
Maybe I've misinterpreted this, I've got what I thought was a fix for this locally but it's not done what I thought 🤔

**Comment by jamietanna** [comment]
Looks like I've misinterpreted this, this is for path params that could be JSON, is that right?

**Comment by deepmap-marcinr** [comment]
It's difficult to infer all of these correctly. I think that the routers will simplify the third case, with charset so that should work, however the first two won't. Perhaps the best way to do this is to have a lookup that's user customizable in the config file.

**Comment by jamietanna** [comment]
If you see my PR, it's fairly straightforward to do this, it may be that I've just misunderstood what we are doing here

**Comment by deepmap-marcinr** [comment]
Given where you have made your change, your code affects only the deserialization of Parameters - not request payloads or responses. My point was - there may be many content types deserializable as json and perhaps a lookup map passed into the code generator might be better than hardcoded heuristics. I've found, since opening up this code, that every single heuristic I have used has been wrong :)
