### ISSUE TITLE
Why are response models private?

### ISSUE THREAD

**Issue by VadimKulagin** [deepmap/oapi-codegen#59]
I want to use API response models from other packages, but for some reason they are now generated privately (their names begin with a small letter):
```go
type getFirstPetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Pet
}
```
Why are they private?

**Comment by lukekhamilton** [comment]
Can you provide the swagger spec you are using?

**Comment by MrWako** [comment]
I've just hit this issue too. It can be seen in the petstore example client [https://github.com/deepmap/oapi-codegen/blob/master/examples/petstore-expanded/petstore-client.gen.go](https://github.com/deepmap/oapi-codegen/blob/master/examples/petstore-expanded/petstore-client.gen.go) with the `FindPetsWithResponse`:
```
func (c *ClientWithResponses) FindPetsWithResponse(ctx context.Context, params *FindPetsParams) (*findPetsResponse, error) {...}
```

My use case is to code generate into a package in the `internal` directory and then import this into a public package. I want to define the interface to the generated `ClientWithResponses` code in the consuming public package but can't due to the private response. Currently I manually create the `ClientWithResponses` interface in the same package as the generated codegen. There's probably a few solutions:

* Modify the response signature and make the response objects public. It would be a breaking change though and probably need a major version bump.
* Auto generate a `ClientWithResponsesInterface` as is already done for the client with the `ClientInterface`

**Comment by jamietanna** [comment]
This is no longer an issue and can be closed: https://github.com/deepmap/oapi-codegen/blob/master/examples/petstore-expanded/petstore-client.gen.go#L425
