### ISSUE TITLE
Last release was a breaking change, should it have not been a v2 release?

### ISSUE THREAD

**Issue by matyat** [deepmap/oapi-codegen#629]
The latest release has changed the cli and is now incompatible with previous invocations. It's an easy fix by adding the `--old-config-style`, but users shouldn't have to do that for a minor release.

**Comment by deefdragon** [comment]
As I said in #630, it took me much longer than it should to figure out why my config and CI/CD pipeline was broken. This REALLY should be a V2. Please release a revert as v1.12 so that updates pull the old format (including a deprecation warning would be best), and THEN push the new changes as a separate v2 module.
