### ISSUE TITLE
readOnly and pointers

### ISSUE THREAD

**Issue by Southclaws** [deepmap/oapi-codegen#730]
I've noticed that marking a property as `readOnly` results in the struct field becoming a pointer. This seems weird, is there a reason for this?

**Comment by jamietanna** [comment]
My understanding is that this is due to the `readOnly` being useful when you're re-using the same object between request and response, therefore we're making it optional on the generated struct.

An alternative could be to produce multiple objects, but as this has been removed in OpenAPI 3.1, it may not be worth the investment.

**Comment by florentchauveau** [comment]
Check this: https://github.com/deepmap/oapi-codegen/issues/604#issuecomment-1145798219

The [PR](https://github.com/deepmap/oapi-codegen/pull/605) has been merged in master.

**Comment by florentchauveau** [comment]
It's a pointer because you're not supposed to set the value on **client side**.

**Comment by Southclaws** [comment]
Ah client, kind of makes sense. Is this to just make it harder to set literal values? Because with a pointer you can obviously still just do `&xyz`.
