### ISSUE TITLE
chi-server generated API sets content type of text/plain

### ISSUE THREAD

**Issue by the42** [deepmap/oapi-codegen#97]
1. Problem

When I generate the server code for chi, the response is always of type text/plain. Even setting

import	"github.com/go-chi/render"

r := chi.NewRouter()
r.Use(render.SetContentType(render.ContentTypeJSON))

produces content-type text/pain.

2. Expected
Either response is of content-type application/json or respects set headers

**Comment by dannymidnight** [comment]
Hey @the42 I think your issue is more related to `github.com/go-chi/render`.

Having a look at the [`render.SetContentType()`](https://github.com/go-chi/render/blob/master/content_type.go#L48-L56) middleware it doesn't appear to specifically set the `Content-Type` header but rather an enum value into the request context.

An alternative approach would be adding your own middleware 

e.g.
```go
r.Use(func(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        w.Header().Set("Content-Type", "application/json")
        next.ServeHTTP(w, r)
    })
})
```

**Comment by the42** [comment]
works great, thank you!
